# Generated by Django 4.2.7 on 2023-11-21 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_client_alter_userreceived_id_delete_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreceived',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received', to='main.client'),
        ),
    ]
