# Generated by Django 4.2.7 on 2023-11-21 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userreceived_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreceived',
            old_name='user',
            new_name='client',
        ),
    ]
